services:
    vue:
        command: ["npm", "run", "dev"]
        volumes:
            - ./vue:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
    nginx:
        environment:
            - DEV_MODE=true
            - SEED_DB=true
        ports:
            - 80:80
    certbot:
        profiles:
            - disabled
