services:
    vue:
        command: ["npm", "run", "dev"]
        volumes:
            - ./vue:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
    backend:
        environment:
            - SPOTIFY_REDIRECT_URI=https://localhost/api/spotify/callback
            - GQL_PLAYGROUND=true
            - GQL_INTROSPECTION=true
    nginx:
        environment:
            - DEV_MODE=true
            - SEED_DB=true
        ports:
            - 80:80
            - 443:443
    hasura:
        environment:
            HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
            HASURA_GRAPHQL_DEV_MODE: "true"
    certbot:
        profiles:
            - disabled
