#!/bin/bash

# Go to deployment directory

# Pull latest changes from remote repository

# Start docker applications
docker compose up -d helloworld
docker compose up -d nginx
docker compose up -d certbot
