name: Deploy with Docker Compose

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Pull changes
              working-directory: /home/adamf/deploy/web_server
              run: git pull gitea main

            - name: Run docker compose up
              working-directory: /home/adamf/deploy/web_server
              env:
                  DOCKER_API_VERSION: "1.41"
              run: docker compose up -d --build --remove-orphans
