// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"adam-french.co.uk/backend/models"
)

type AuthPayload struct {
	User *models.User `json:"user"`
}

type CreateActivityInput struct {
	Type string  `json:"type"`
	Name string  `json:"name"`
	Link *string `json:"link,omitempty"`
}

type CreateFavoriteInput struct {
	Type string  `json:"type"`
	Name string  `json:"name"`
	Link *string `json:"link,omitempty"`
}

type CreateJobApplicationInput struct {
	JobTitle  string     `json:"jobTitle"`
	Company   string     `json:"company"`
	Location  *string    `json:"location,omitempty"`
	URL       *string    `json:"url,omitempty"`
	Status    string     `json:"status"`
	Notes     *string    `json:"notes,omitempty"`
	AppliedAt *time.Time `json:"appliedAt,omitempty"`
}

type CreatePostInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type CreateUserInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type GiteaFeedItem struct {
	AvatarURL     string    `json:"avatarUrl"`
	RepoURL       string    `json:"repoUrl"`
	RepoName      string    `json:"repoName"`
	OpType        string    `json:"opType"`
	CommitMessage string    `json:"commitMessage"`
	CreatedAt     time.Time `json:"createdAt"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type SpotifyAlbum struct {
	Name   string          `json:"name"`
	Images []*SpotifyImage `json:"images"`
}

type SpotifyArtist struct {
	Name string `json:"name"`
}

type SpotifyImage struct {
	URL string `json:"url"`
}

type SpotifyPlaying struct {
	Playing bool          `json:"playing"`
	Track   *SpotifyTrack `json:"track,omitempty"`
}

type SpotifyRecentItem struct {
	Track    *SpotifyTrack `json:"track"`
	PlayedAt time.Time     `json:"playedAt"`
}

type SpotifyTrack struct {
	Name    string           `json:"name"`
	Artists []*SpotifyArtist `json:"artists"`
	Album   *SpotifyAlbum    `json:"album"`
}

type SteamGame struct {
	AppID           int    `json:"appId"`
	Name            string `json:"name"`
	Playtime2Weeks  int    `json:"playtime2Weeks"`
	PlaytimeForever int    `json:"playtimeForever"`
	HeaderImageURL  string `json:"headerImageUrl"`
}

type SteamStatus struct {
	Online      bool         `json:"online"`
	RecentGames []*SteamGame `json:"recentGames"`
}

type UpdateJobApplicationInput struct {
	JobTitle  *string    `json:"jobTitle,omitempty"`
	Company   *string    `json:"company,omitempty"`
	Location  *string    `json:"location,omitempty"`
	URL       *string    `json:"url,omitempty"`
	Status    *string    `json:"status,omitempty"`
	Notes     *string    `json:"notes,omitempty"`
	AppliedAt *time.Time `json:"appliedAt,omitempty"`
}

type UpdatePostInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}
