<template>
    <div class="flex-col center-content">
        <h2>favs</h2>
        <div class="fill scroll">
            <table>
                <tbody>
                    <tr>
                        <th>Daioh</th>
                        <td>Tomo</td>
                    </tr>
                    <tr>
                        <th>Color</th>
                        <td>Teal</td>
                    </tr>
                    <tr>
                        <th>Pet</th>
                        <td>Cat</td>
                    </tr>
                    <tr>
                        <th>Subject</th>
                        <td>Math</td>
                    </tr>
                    <tr>
                        <th>Drink</th>
                        <td>Monster</td>
                    </tr>
                    <tr>
                        <th>Sport</th>
                        <td>Running</td>
                    </tr>
                    <tr>
                        <th>Anime</th>
                        <td>Evangelion</td>
                    </tr>
                    <tr>
                        <th>Fruit</th>
                        <td>Satsumas</td>
                    </tr>
                    <tr>
                        <th>Vegetable</th>
                        <td>Cucumber</td>
                    </tr>
                    <tr>
                        <th>Hobby</th>
                        <td>Climbing</td>
                    </tr>
                    <tr>
                        <th>Season</th>
                        <td>Summer</td>
                    </tr>
                    <tr>
                        <th>Language</th>
                        <td>Rust</td>
                    </tr>
                    <tr>
                        <th>OS</th>
                        <td>Linux</td>
                    </tr>
                    <tr>
                        <th>Ingredient</th>
                        <td>Eggs</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</template>
