package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"time"

	"adam-french.co.uk/backend/graph/model"
	"adam-french.co.uk/backend/services"
)

// GiteaFeed is the resolver for the giteaFeed field.
func (r *queryResolver) GiteaFeed(ctx context.Context) (*model.GiteaFeedItem, error) {
	if r.Store.GiteaFeedFresh() {
		return mapGiteaFeed(r.Store.GiteaFeed), nil
	}

	feed, err := services.FetchLatestFeed(r.Store.GiteaHost, r.Store.GiteaPort)
	if err != nil {
		return nil, err
	}
	if feed == nil {
		return nil, nil
	}

	r.Store.GiteaFeed = feed
	r.Store.GiteaFeedFetchedAt = time.Now()

	return mapGiteaFeed(feed), nil
}
