package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"adam-french.co.uk/backend/graph/model"
	"adam-french.co.uk/backend/services"
)

// GiteaFeed is the resolver for the giteaFeed field.
func (r *queryResolver) GiteaFeed(ctx context.Context) (*model.GiteaFeedItem, error) {
	// One-minute cache on the Store, shared by every visitor, so a busy home
	// page does not hammer the Gitea container.
	if cached, ok := r.Store.CachedGiteaFeed(); ok {
		return mapGiteaFeed(cached), nil
	}

	feed, err := services.FetchLatestFeed(r.Store.GiteaHost, r.Store.GiteaPort)
	if err != nil {
		return nil, err
	}
	// FetchLatestFeed returns (nil, nil) for an empty feed; mapGiteaFeed
	// would dereference it, so return null to the client instead. The cache
	// is deliberately not written in that case, so an empty feed is retried
	// on the next request.
	if feed == nil {
		return nil, nil
	}

	r.Store.SetGiteaFeed(feed)

	return mapGiteaFeed(feed), nil
}
