package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"adam-french.co.uk/backend/models"
)

// ID is the resolver for the id field.
func (r *messageResolver) ID(ctx context.Context, obj *models.Message) (int, error) {
	return int(obj.ID), nil
}

// AuthorID is the resolver for the authorId field.
// AuthorID is the resolver for the authorId field. The value is the chat
// hub's per-connection counter, not a User id — see models.Message.
func (r *messageResolver) AuthorID(ctx context.Context, obj *models.Message) (int, error) {
	return int(obj.AuthorID), nil
}

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context) ([]*models.Message, error) {
	// Non-admins get the public subset rather than an error, so the chat
	// history loads for everyone. The same filter is applied to the history
	// replayed over the WebSocket (services.HandleWebSocket) — change one and
	// the other must change too.
	//
	// Note the ordering differs between the two: newest first here, oldest
	// first over the socket.
	var messages []models.Message
	query := r.Store.DB.Order("created_at DESC")
	if !IsAdminFromCtx(ctx) {
		query = query.Where("private = ?", false)
	}
	if err := query.Find(&messages).Error; err != nil {
		return nil, err
	}
	return ptrs(messages), nil
}

// Message returns MessageResolver implementation.
func (r *Resolver) Message() MessageResolver { return &messageResolver{r} }

type messageResolver struct{ *Resolver }
