package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"adam-french.co.uk/backend/models"
)

// ID is the resolver for the id field.
func (r *messageResolver) ID(ctx context.Context, obj *models.Message) (int, error) {
	return int(obj.ID), nil
}

// AuthorID is the resolver for the authorId field.
func (r *messageResolver) AuthorID(ctx context.Context, obj *models.Message) (int, error) {
	return int(obj.AuthorID), nil
}

// Message returns MessageResolver implementation.
func (r *Resolver) Message() MessageResolver { return &messageResolver{r} }

type messageResolver struct{ *Resolver }
