package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"

	"adam-french.co.uk/backend/graph/model"
	"adam-french.co.uk/backend/models"
)

// CreatePlace is the resolver for the createPlace field.
func (r *mutationResolver) CreatePlace(ctx context.Context, input model.CreatePlaceInput) (*models.Place, error) {
	if !IsAdminFromCtx(ctx) {
		return nil, fmt.Errorf("admin access required")
	}
	place := models.Place{
		Title:    input.Title,
		Location: input.Location,
		Notes:    input.Notes,
		ImageURL: input.ImageURL,
		Category: input.Category,
		Cost:     input.Cost,
	}
	if input.Priority != nil {
		place.Priority = *input.Priority
	}
	if input.Done != nil {
		place.Done = *input.Done
	}
	if err := r.Store.DB.Create(&place).Error; err != nil {
		return nil, err
	}
	return &place, nil
}

// UpdatePlace is the resolver for the updatePlace field.
func (r *mutationResolver) UpdatePlace(ctx context.Context, id int, input model.UpdatePlaceInput) (*models.Place, error) {
	if !IsAdminFromCtx(ctx) {
		return nil, fmt.Errorf("admin access required")
	}
	var place models.Place
	if err := r.Store.DB.First(&place, id).Error; err != nil {
		return nil, err
	}
	if input.Title != nil {
		place.Title = *input.Title
	}
	if input.Location != nil {
		place.Location = input.Location
	}
	if input.Notes != nil {
		place.Notes = input.Notes
	}
	if input.ImageURL != nil {
		place.ImageURL = input.ImageURL
	}
	if input.Category != nil {
		place.Category = input.Category
	}
	if input.Cost != nil {
		place.Cost = input.Cost
	}
	if input.Priority != nil {
		place.Priority = *input.Priority
	}
	if input.Done != nil {
		place.Done = *input.Done
	}
	if err := r.Store.DB.Save(&place).Error; err != nil {
		return nil, err
	}
	return &place, nil
}

// DeletePlace is the resolver for the deletePlace field.
func (r *mutationResolver) DeletePlace(ctx context.Context, id int) (*models.Place, error) {
	if !IsAdminFromCtx(ctx) {
		return nil, fmt.Errorf("admin access required")
	}
	var place models.Place
	if err := r.Store.DB.First(&place, id).Error; err != nil {
		return nil, err
	}
	if err := r.Store.DB.Delete(&place).Error; err != nil {
		return nil, err
	}
	return &place, nil
}

// ID is the resolver for the id field.
func (r *placeResolver) ID(ctx context.Context, obj *models.Place) (int, error) {
	return int(obj.ID), nil
}

// Places is the resolver for the places field.
func (r *queryResolver) Places(ctx context.Context) ([]*models.Place, error) {
	var places []models.Place
	if err := r.Store.DB.Order("done ASC, priority DESC, created_at DESC").Find(&places).Error; err != nil {
		return nil, err
	}
	result := make([]*models.Place, len(places))
	for i := range places {
		result[i] = &places[i]
	}
	return result, nil
}

// Place returns PlaceResolver implementation.
func (r *Resolver) Place() PlaceResolver { return &placeResolver{r} }

type placeResolver struct{ *Resolver }
