package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"adam-french.co.uk/backend/models"
)

// ID is the resolver for the id field.
func (r *rowingResolver) ID(ctx context.Context, obj *models.Rowing) (int, error) {
	return int(obj.ID), nil
}

// Time is the resolver for the time field.
func (r *rowingResolver) Time(ctx context.Context, obj *models.Rowing) (int, error) {
	return int(obj.Time), nil
}

// Distance is the resolver for the distance field.
func (r *rowingResolver) Distance(ctx context.Context, obj *models.Rowing) (int, error) {
	return int(obj.Distance), nil
}

// Rowing returns RowingResolver implementation.
func (r *Resolver) Rowing() RowingResolver { return &rowingResolver{r} }

type rowingResolver struct{ *Resolver }
