type JobApplication {
  id: ID!
  createdAt: Time!
  updatedAt: Time!
  jobTitle: String!
  company: String!
  location: String
  url: String
  status: String!
  notes: String
  appliedAt: Time
}

input CreateJobApplicationInput {
  jobTitle: String!
  company: String!
  location: String
  url: String
  status: String!
  notes: String
  appliedAt: Time
}

input UpdateJobApplicationInput {
  jobTitle: String
  company: String
  location: String
  url: String
  status: String
  notes: String
  appliedAt: Time
}

extend type Query {
  jobApplications: [JobApplication!]!
  jobApplication(id: ID!): JobApplication
}

extend type Mutation {
  createJobApplication(input: CreateJobApplicationInput!): JobApplication!
  updateJobApplication(id: ID!, input: UpdateJobApplicationInput!): JobApplication!
  deleteJobApplication(id: ID!): Boolean!
}
